version: "3"
networks:
  monero-pool:
    external: false

volumes:
  monero:
    external: false
  p2pool:
    external: false

services:
  monero:
    build:
      context: docker/monero
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /run/monero
    networks:
      - monero-pool
    volumes:
      - monero:/root/.bitmonero
    ports:
      - "18080:18080"
    command: >-
      --p2p-external-port "${MONERO_EXTERNAL_P2P_PORT}"

  p2pool:
    build:
      context: docker/p2pool
      args:
        ref: origin/master
    restart: always
    tty: true
    stdin_open: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - monero-pool
    depends_on:
      - monero
    volumes:
      - p2pool:/p2pool/data:rw
      - "${HUGEPAGES_MOUNT}:/dev/hugepages:rw"
    ports:
      - "${P2POOL_STRATUM_PORT}:${P2POOL_STRATUM_PORT}"
      - "${P2POOL_P2P_PORT}:${P2POOL_P2P_PORT}"
    command: >-
      --wallet "${P2POOL_WALLET_ADDRESS}"
      --stratum "0.0.0.0:${P2POOL_STRATUM_PORT}" --p2p "0.0.0.0:${P2POOL_P2P_PORT}"
      --addpeers "${P2POOL_SEED_PEERS}"
      --loglevel "${P2POOL_LOG_LEVEL}"
